[package]
name = "chimera-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
no_deadlocks = { version = "1.3", optional = true}
thiserror = "1.0"
itertools = "0.13"

utils-macros = { path = "./utils-macros" }

[features]
no_deadlocks = ["dep:no_deadlocks"]
